config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers:{
    registrations: 'users/registrations',
    sessions: 'users/sessions',
  }

  namespace :api do
    post :upload_image, to: 'utils#upload_image'
    resources :stories, only: [] do
      member do
        post :clap  # /stories/:id/clap
        post :bookmark #/stories/:id/bookmark
      end
    end

    resources :users, only: [] do
      member do
        post :follow #/users/:id/follow
      end
    end
  end

  resources :users, only: [] do
    collection do
      get :pricing #/users/pricing
      get :payment #/users/payment
      post :pay    #/user/pay
    end
  end  
  


  resources :stories do
    resources :comments, only: [:create]
  end






  get '@:username/:story_id', to: 'pages#show', as: 'story_page'
  
  get '@:username', to: 'pages#user', as: 'user_page'

  get '/demo', to: 'pages#demo'

  root 'pages#index'
end

app/views/pages/_bookmark_story.html.erb
<section class="columns">
  <section class="column is-4">
    <%= link_to story_page_path(story.user.username, story), class: 'has-text-grey-dark' do %>
      <figure class="has-text-centered">
        <% if story.cover_image.attached?  %>
          <%= image_tag story.cover_image.variant(resize: '100x100') %>
        <% else %>
          <img src="https://fakeimg.pl/100x100/f0f0f0?text=NoCover" alt="">            
        <% end %>
      </figure>
    <% end %>
  </section>
  <section class="column">
    <%= link_to story_page_path(story.user.username, story), class: 'has-text-grey-dark' do %>
      <h2 class="title is-size-5">
        <p>
          <%= story.title %>
          <i class="fas fa-bookmark has-text-danger is-size-6"></i>
        </p>        
      </h2>
    <% end %>
    <p class="content"><%= strip_tags(story.content).truncate(50) %></p>
    <footer>
      <p><%= link_to story.user.username, user_page_path(story.user.username), class: 'has-text-bule-dark' %> | <%= time_ago_in_words(story.updated_at) %> ago</p>
    </footer>
  </section>
</section>

app/views/pages/_comment.html.erb
<article class="comment">
    <span class="profile">
        <%= image_tag comment.user.avatar.variant(resize: '50x50') if comment.user.avatar.attached? %>
        <span class="username"><%= comment.user.username %></span>
    </span>
    <%= simple_format(comment.content) %>
</article>

app/views/pages/_comment_area.html.erb
<section class="comment-editor">
    <% if user_signed_in? %>    
        <%= form_with model: comment, url: story_comments_path(story), class: 'comment_form', remote: true do |form| %>
            <%= form.text_area :content, row: 5, class: 'textarea is-small' %>
            <%= form.button "送出", class: 'button is-primary is-fullwidth' %>
        <% end %>
    <% else %>
        <%= link_to "會員登入", new_user_session_path, class: 'button is-success'%>
        <%= link_to "會員註冊", new_user_registration_path, class: 'button is-info'%>
    <% end %>
</section>

app/views/pages/_follow_user.erb
<article class="media">
  <figure class="media-left">
    <% if user.avatar.attached? %>
      <%= image_tag user.avatar.variant(resize: '75x75') %>
    <% else %>
      <img src="https://fakeimg.pl/75x75/f0f0f0?text=NoAvatar">
    <% end %>
  </figure>
   
  <div class="media-content">

    <h2 class="title is-4"><%= link_to user.username, user_page_path(user.username) %></h2>
    <p class="content">
      <%= link_to user.stories.last.title, story_page_path(user.username, user.stories.last), class: 'has-text-grey-dark' %>
    </p>
    <footer>
      <p><%= time_ago_in_words(user.stories.last.updated_at) %> ago</p>
    </footer>
  </div>
</article>

app/views/pages/_popular_other.html.erb
<section class="columns">
  <section class="column is-4">
    <%= link_to story_page_path(story.user.username, story), class: 'has-text-grey-dark' do %>
      <figure class="has-text-centered">
        <% if story.cover_image.attached?  %>
          <%= image_tag story.cover_image.variant(resize: '150x150') %>
        <% else %>
          <img src="https://fakeimg.pl/150x150/f0f0f0?text=NoCover" alt="">            
        <% end %>
      </figure>
    <% end %>
  </section>
  <section class="column">
    <%= link_to story_page_path(story.user.username, story), class: 'has-text-grey-dark' do %>
      <h2 class="title is-size-4">
        <p><%= story.title %></p>
        <i class="fas fa-hand-spock has-text-primary is-size-6"></i>
        <span class="clapCount has-text-primary is-size-6"><%= story.clap %></span>
      </h2>
    <% end %>
    <p class="content"><%= strip_tags(story.content).truncate(50) %></p>
    <footer>
      <p><%= link_to story.user.username, user_page_path(story.user.username), class: 'has-text-bule-dark' %> | <%= time_ago_in_words(story.updated_at) %> ago</p>
    </footer>    
  </section>
</section>

app/views/pages/_popular_top.html.erb
<article>
  <%= link_to story_page_path(story.user.username, story), class: 'has-text-grey-dark' do %>
    <figure class="image">
      <% if story.cover_image.attached?  %>
      <%= image_tag story.cover_image.variant(resize: '150x150') %>
    <% else %>
      <img src="https://fakeimg.pl/150x150/f0f0f0?text=NoCover" alt="">            
    <% end %>
    </figure>
    <h2 class="title is-size-4">
      <p><%= story.title %></p>
      <i class="fas fa-hand-spock has-text-primary is-size-6"></i>
      <span class="clapCount has-text-primary is-size-6"><%= story.clap %></span>
    </h2>
  <% end %>
  <p class="content"><%= strip_tags(story.content).truncate(300) %></p>
  <footer>
    <p><%= link_to story.user.username, user_page_path(story.user.username), class: 'has-text-blue-dark' %> | <%= time_ago_in_words(story.updated_at) %> ago</p>
  </footer>
</article>

app/views/pages/demo.html.erb
<div data-controller="demo">
    <input type="text" data-target="demo.content">
    <button data-action="click->demo#pushme">按我</button>
</div>

<div data-controller="demo">
    <input type="text" data-target="demo.content">
    <button data-action="click->demo#pushit">按它</button>
</div>

app/views/pages/index.html.erb
  <section class="section">
  <div class="container">
    <section class="columns">
      <!-- left and middle -->
      <section class="column is-9">
        <h1 class="title is-2 has-text-danger" >Popular on Medium</h1>
        <section class="columns">
          <!-- left -->
          <section class="column is-6">
            <%= render 'popular_top', story: @stories_clap.first unless @stories_clap.first.nil? %>
          </section>
          <!-- left -->
          <!-- middle -->
          <section class="column">
            <% 1.upto(3) do |index|%>
              <%= render 'popular_other', story: @stories_clap[index] unless @stories_clap[index].nil? %>
            <% end %>
          </section>
          <!-- middle -->
        </section>
      </section>
      <!-- left and middle -->
      <!-- right -->
      <section class="column">
        <h1 class="title is-3 has-text-danger" >Followed Author</h1>
        <% if user_signed_in? %>
          <% @follow_users.each do |user| %>
            <%= render 'follow_user', user: user %>
          <% end %>
        <% else %>
          <h1 class="title is-4 has-text-danger" >Please login to follow</h1>
        <% end %>
      </section>
      <!-- right -->
    </section>

    <hr>

    <section class="columns">
      <!-- article list -->
      <section class="column is-two-thirds">
        <h1 class="title is-3 has-text-danger" >Article List</h1>
        <% @stories.each do |story|%>
            <article class="media">
                <div class="media-content">
                  <h2 class="title is-4"><%= link_to story.title, story_page_path(story.user.username, story), class: 'has-text-grey-dark' %></h2>
                  <p class="content"><%= strip_tags(story.content).truncate(200) %></p>
                  <footer>
                    <p><%= link_to story.user.username, user_page_path(story.user.username), class: 'has-text-blue-dark' %> | <%= time_ago_in_words(story.updated_at) %> ago</p>
                  </footer>
                </div>
                <% if story.cover_image.attached? %>
                  <figure class="media-right">
                    <%= image_tag story.cover_image.variant(resize: '150x150') %>
                  </figure>
                <% end %>
            </article>
        <% end %>
      </section>
      <!-- article list -->

      <section class="column">
        <h2 class="title is-4 has-text-danger">Bookmarked Story</h2>
        <hr>
        <% if user_signed_in? %>
          <% @bookmark_stories.each do |story| %>
            <%= render 'bookmark_story', story: story %>
          <% end %>
        <% else %>
          <h1 class="title is-4 has-text-danger" >Please login to favorite</h1>
        <% end %>
      </section>
    </section>
  </div>
</section>

app/views/pages/show.html.erb
<section class="columns has-text-centered story-content">
  <section class="column is-offset-2 is-8">
    <h1 class="title"><%= @story.title %></h1>

    <span class="profile", data-controller="user">
      <%= image_tag @story.user.avatar.variant(resize: '50x50'), class: 'avatar' if @story.user.avatar.attached? %>
      <span class="username"><%= @story.user.username %></span>
      <%= link_to '#', class: "follow-button", 
                        data: { action: "user#follow",
                                user: @story.user.id,
                                target: "user.followButton"} do %>
        <%= (user_signed_in? && current_user.follow?(@story.user)? 'Followed' : 'Follow') %>
      <% end %>

      <%= link_to "#", class: "bookmark-button", data: { action: 'user#bookmark', slug: @story.slug } do %>
        <% if (user_signed_in? && current_user.bookmark?(@story)) %>  
          <i class="fas fa-bookmark", data-target= 'user.bookmark' ></i>
        <% else %>
          <i class="far fa-bookmark", data-target= 'user.bookmark' ></i>
        <% end %>
      <% end %>
    </span>
    

    <article class="content">
        <% if @story.cover_image.attached? %>      
            <%= image_tag @story.cover_image.variant(resize: '1000x500'), class: 'cover-image' %>
        <% end %>
        <!-- <%= simple_format(@story.content) %> #simple_format會把css吃掉 -->
        <%= @story.content.html_safe %>
      <footer data-controller="story">
        <%= link_to "#", class: 'clapButton is-size-2 has-text-primary', data: { action: 'story#addClap', slug: @story.slug } do %>  
          <i class="fas fa-hand-spock"></i>
          <span class="clapCount", data-target='story.clapCount'><%= @story.clap %></span>
        <% end %>
      </footer>
    </article>
    <hr>
    <section class="comments">
      <h2>留言</h2>

      <%= render 'comment_area', story: @story, comment: @comment %>

      <section class="comment-list">
        <%= render partial: 'comment', collection: @comments %>
      </section>
    </section>
  </section>
</section>

app/views/pages/user.html.erb
<section class="column is-offset-2 is-8">
	<h1 class='title has-text-danger'><%= @user.username %> Story list</h1>
	<% @user_stories.each do |story| %>
		<article class="media">
			<div class="media-content">
				<h2 class="title is-4"><%= link_to story.title, story_page_path(story.user.username, story), class: 'has-text-grey-dark' %></h2>
				<p class="content"><%= strip_tags(story.content).truncate(200) %></p>
				<footer>
				<p>Updated at : <%= time_ago_in_words(story.updated_at) %> ago</p>
				</footer>
			</div>
			<% if story.cover_image.attached? %>
				<figure class="media-right">
					<%= image_tag story.cover_image.variant(resize: '150x150') %>
				</figure>
			<% end %>
		</article>
	<% end %>
</section>